/* Generated By:JavaCC: Do not edit this line. BeanFactoryLanguageParserConstants.java */
package org.springmodules.beans.factory.bfl.parser;

public interface BeanFactoryLanguageParserConstants {

  int EOF = 0;
  int NEW = 6;
  int ABSTRACT = 7;
  int CHILD_OF = 8;
  int PROTOTYPE = 9;
  int LAZY = 10;
  int DESCRIPTION_FOR = 11;
  int INIT_METHOD_FOR = 12;
  int DESTROY_METHOD_FOR = 13;
  int DEPENDS_ON = 14;
  int SET_AUTOWIRE_FOR = 15;
  int TO = 16;
  int NONE = 17;
  int BY_NAME = 18;
  int BY_TYPE = 19;
  int CONSTRUCTOR = 20;
  int AUTODETECT = 21;
  int IMPORT = 22;
  int ALIAS_FOR = 23;
  int NUM = 24;
  int STRING = 25;
  int IDENTIFIER = 26;
  int LETTER = 27;
  int DIGIT = 28;
  int CLASS_NAME = 29;
  int PATH_ELEMENT = 30;
  int BEAN_NAME = 31;
  int PROPERTY = 32;
  int HERE_STRING_START_OPERATOR = 33;
  int CLASS_PATH = 34;
  int HERE_STRING_START_TOKEN = 35;
  int HERE_STRING_TOKEN1 = 36;
  int HERE_STRING_TOKEN2 = 37;
  int HERE_STRING_NEW_LINE_TOKEN = 38;
  int HERE_STRING_END_TOKEN = 39;
  int HERE_STRING_CONTINUE_TOKEN = 40;

  int DEFAULT = 0;
  int HERE_STRING_START = 1;
  int HERE_STRING = 2;
  int HERE_STRING_END = 3;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"NEW\"",
    "\"ABSTRACT\"",
    "\"CHILD OF\"",
    "\"PROTOTYPE\"",
    "\"LAZY\"",
    "\"DESCRIPTION FOR\"",
    "\"INIT METHOD FOR\"",
    "\"DESTROY METHOD FOR\"",
    "\"DEPENDS ON\"",
    "\"SET AUTOWIRE FOR\"",
    "\"TO\"",
    "<NONE>",
    "\"BY NAME\"",
    "\"BY TYPE\"",
    "\"CONSTRUCTOR\"",
    "\"AUTODETECT\"",
    "\"IMPORT\"",
    "\"ALIAS FOR\"",
    "<NUM>",
    "<STRING>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "<CLASS_NAME>",
    "<PATH_ELEMENT>",
    "<BEAN_NAME>",
    "<PROPERTY>",
    "\"<<<\"",
    "<CLASS_PATH>",
    "<HERE_STRING_START_TOKEN>",
    "<HERE_STRING_TOKEN1>",
    "\"\\n\"",
    "\"\\n\"",
    "<HERE_STRING_END_TOKEN>",
    "<HERE_STRING_CONTINUE_TOKEN>",
    "\"=\"",
    "\";\"",
    "\",\"",
    "\"[\"",
    "\"]\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"->\"",
    "\"+\"",
  };

}
