/* Generated By:JavaCC: Do not edit this line. ValangParserConstants.java */
package org.springmodules.validation.valang;

public interface ValangParserConstants {

  int EOF = 0;
  int AND = 5;
  int OR = 6;
  int NOT = 7;
  int BETWEEN = 8;
  int NOT_BETWEEN = 9;
  int IN = 10;
  int NOT_IN = 11;
  int IS_NULL = 12;
  int IS_NOT_NULL = 13;
  int HAS_TEXT = 14;
  int HAS_NO_TEXT = 15;
  int HAS_LENGTH = 16;
  int HAS_NO_LENGTH = 17;
  int IS_BLANK = 18;
  int IS_NOT_BLANK = 19;
  int IS_UPPER_CASE = 20;
  int IS_NOT_UPPER_CASE = 21;
  int IS_LOWER_CASE = 22;
  int IS_NOT_LOWER_CASE = 23;
  int IS_WORD = 24;
  int IS_NOT_WORD = 25;
  int TRUE = 26;
  int FALSE = 27;
  int MORE_THAN_OR_EQUAL = 28;
  int MORE_THAN = 29;
  int LESS_THAN_OR_EQUAL = 30;
  int LESS_THAN = 31;
  int NOT_EQUAL = 32;
  int EQUALS = 33;
  int ADD = 34;
  int SUBTRACT = 35;
  int MULTIPLY = 36;
  int DIVIDE = 37;
  int MOD = 38;
  int NUM = 39;
  int STRING = 40;
  int DATE = 41;
  int DOT = 42;
  int UNDERSCORE = 43;
  int DIGIT = 44;
  int LOWERLETTER = 45;
  int UPPERLETTER = 46;
  int PATH = 47;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"AND\"",
    "\"OR\"",
    "\"NOT\"",
    "\"BETWEEN\"",
    "\"NOT BETWEEN\"",
    "\"IN\"",
    "\"NOT IN\"",
    "<IS_NULL>",
    "<IS_NOT_NULL>",
    "\"HAS TEXT\"",
    "\"HAS NO TEXT\"",
    "\"HAS LENGTH\"",
    "\"HAS NO LENGTH\"",
    "\"IS BLANK\"",
    "\"IS NOT BLANK\"",
    "<IS_UPPER_CASE>",
    "<IS_NOT_UPPER_CASE>",
    "<IS_LOWER_CASE>",
    "<IS_NOT_LOWER_CASE>",
    "\"IS WORD\"",
    "\"IS NOT WORD\"",
    "<TRUE>",
    "<FALSE>",
    "<MORE_THAN_OR_EQUAL>",
    "\">\"",
    "<LESS_THAN_OR_EQUAL>",
    "\"<\"",
    "<NOT_EQUAL>",
    "<EQUALS>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "<DIVIDE>",
    "<MOD>",
    "<NUM>",
    "<STRING>",
    "<DATE>",
    "\".\"",
    "\"_\"",
    "<DIGIT>",
    "<LOWERLETTER>",
    "<UPPERLETTER>",
    "<PATH>",
    "\"{\"",
    "\":\"",
    "\",\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\"@\"",
    "\"!\"",
    "\"?\"",
    "\"$\"",
  };

}
