/* Generated By:JavaCC: Do not edit this line. ValangParserConstants.java */
/*
 * Copyright 2004-2005 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.springmodules.validation.valang.parser;

public interface ValangParserConstants {

  int EOF = 0;
  int AND = 5;
  int OR = 6;
  int NOT = 7;
  int BETWEEN = 8;
  int NOT_BETWEEN = 9;
  int IN = 10;
  int NOT_IN = 11;
  int IS_NULL = 12;
  int IS_NOT_NULL = 13;
  int HAS_TEXT = 14;
  int HAS_NO_TEXT = 15;
  int HAS_LENGTH = 16;
  int HAS_NO_LENGTH = 17;
  int IS_BLANK = 18;
  int IS_NOT_BLANK = 19;
  int IS_UPPER_CASE = 20;
  int IS_NOT_UPPER_CASE = 21;
  int IS_LOWER_CASE = 22;
  int IS_NOT_LOWER_CASE = 23;
  int IS_WORD = 24;
  int IS_NOT_WORD = 25;
  int TRUE = 26;
  int FALSE = 27;
  int MORE_THAN_OR_EQUAL = 28;
  int MORE_THAN = 29;
  int LESS_THAN_OR_EQUAL = 30;
  int LESS_THAN = 31;
  int NOT_EQUAL = 32;
  int EQUALS = 33;
  int ADD = 34;
  int SUBTRACT = 35;
  int MULTIPLY = 36;
  int DIVIDE = 37;
  int MOD = 38;
  int NUM = 39;
  int STRING = 40;
  int DATE = 41;
  int DOT = 42;
  int UNDERSCORE = 43;
  int DIGIT = 44;
  int POSITIVE_INTEGER = 45;
  int LOWERLETTER = 46;
  int UPPERLETTER = 47;
  int PLAIN_PATH_ELEMENT = 48;
  int INDEXED_PATH_ELEMENT = 49;
  int FUNCTION_NAME = 50;
  int PATH = 51;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"AND\"",
    "\"OR\"",
    "\"NOT\"",
    "<BETWEEN>",
    "<NOT_BETWEEN>",
    "<IN>",
    "<NOT_IN>",
    "<IS_NULL>",
    "<IS_NOT_NULL>",
    "\"HAS TEXT\"",
    "\"HAS NO TEXT\"",
    "\"HAS LENGTH\"",
    "\"HAS NO LENGTH\"",
    "\"IS BLANK\"",
    "\"IS NOT BLANK\"",
    "<IS_UPPER_CASE>",
    "<IS_NOT_UPPER_CASE>",
    "<IS_LOWER_CASE>",
    "<IS_NOT_LOWER_CASE>",
    "\"IS WORD\"",
    "\"IS NOT WORD\"",
    "<TRUE>",
    "<FALSE>",
    "<MORE_THAN_OR_EQUAL>",
    "<MORE_THAN>",
    "<LESS_THAN_OR_EQUAL>",
    "<LESS_THAN>",
    "<NOT_EQUAL>",
    "<EQUALS>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "<DIVIDE>",
    "<MOD>",
    "<NUM>",
    "<STRING>",
    "<DATE>",
    "\".\"",
    "\"_\"",
    "<DIGIT>",
    "<POSITIVE_INTEGER>",
    "<LOWERLETTER>",
    "<UPPERLETTER>",
    "<PLAIN_PATH_ELEMENT>",
    "<INDEXED_PATH_ELEMENT>",
    "<FUNCTION_NAME>",
    "<PATH>",
    "\"{\"",
    "\":\"",
    "\",\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\"@\"",
    "\"!\"",
    "\"?\"",
  };

}
